// import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const playfair_display = Playfair_Display({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jamil's Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair_display.className}>
        <Navbar></Navbar>
        <div className="min-h-screen">{children}</div>
        <footer className="bg-gray-400 text-white py-5 text-center">
          This is Footer
        </footer>
      </body>
    </html>
  );
}
